gatling {
  core {
    outputDirectoryBaseName = "saga-orchestrator"
    runDescription = "Async Saga Orchestration Load Test"
    encoding = "utf-8"
    simulationClass = ""
    elFileBodiesCacheMaxCapacity = 200
    rawFileBodiesCacheMaxCapacity = 200
    rawFileBodiesInMemoryMaxSize = 1000
    pebbleFileBodiesCacheMaxCapacity = 200
    feederAdaptiveLoadModeThreshold = 100
    shutdownTimeout = 10000
    extract {
      regex {
        cacheMaxCapacity = 200
      }
      xpath {
        cacheMaxCapacity = 200
      }
      jsonPath {
        cacheMaxCapacity = 200
      }
      css {
        cacheMaxCapacity = 200
      }
    }
    directory {
      simulations = ""
      resources = ""
      reportsOnly = ""
      binaries = ""
      results = "results"
    }
  }
  socket {
    connectTimeout = 10000
    tcpNoDelay = true
    soKeepAlive = false
  }
  netty {
    useNativeTransport = true
    allocator = "pooled"
    maxThreadLocalCharBufferSize = 200000
  }
  ssl {
    useOpenSsl = true
    useOpenSslFinalizers = false
    handshakeTimeout = 10000
    useInsecureTrustManager = false
    enabledProtocols = []
    enabledCipherSuites = []
    sessionCacheSize = 0
    sessionTimeout = 0
    enableSni = true
  }
  charting {
    noReports = false
    maxPlotPerSeries = 1000
    useGroupDurationMetric = false
    indicators {
      lowerBound = 800
      higherBound = 1200
      percentile1 = 50
      percentile2 = 75
      percentile3 = 95
      percentile4 = 99
    }
  }
  http {
    fetchedCssCacheMaxCapacity = 200
    fetchedHtmlCacheMaxCapacity = 200
    perUserCacheMaxCapacity = 200
    warmUpUrl = "https://gatling.io"
    enableGA = true
    ssl {
      keyStore {
        type = ""
        file = ""
        password = ""
        algorithm = ""
      }
      trustStore {
        type = ""
        file = ""
        password = ""
        algorithm = ""
      }
    }
    ahc {
      keepAlive = true
      connectTimeout = 10000
      handshakeTimeout = 10000
      pooledConnectionIdleTimeout = 60000
      readTimeout = 60000
      maxRetry = 2
      requestTimeout = 60000
      useProxyProperties = false
      webSocketMaxFrameSize = 10240000
    }
    dns {
      queryTimeout = 5000
      maxQueriesPerResolve = 6
    }
  }
  jms {
    replyTimeoutScanPeriod = 1000
  }
  data {
    writers = [console, file]
    console {
      light = false
      writePeriod = 5
    }
    file {
      bufferSize = 8192
    }
    leak {
      noActivityTimeout = 30
    }
    graphite {
      light = false
      host = "localhost"
      port = 2003
      protocol = "tcp"
      rootPathPrefix = "gatling"
      bufferSize = 8192
      writePeriod = 1
    }
  }
}
