spring:
  application:
    name: shipping-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8084

logging:
  level:
    com.saga.orchestrator.shipping: DEBUG
