spring:
  application:
    name: saga-orchestrator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/saga_orchestrator_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

#flowable:
#  async-executor-activate: true
#  database-schema-update: true
#  rest:
#    app:
#      authentication-mode: verify-privilege

flowable:
  async-executor:
    enabled: true
    core-pool-size: 10
    max-pool-size: 20
    queue-size: 100
    keep-alive-time: 5000
    default-async-job-acquire-wait-time: 10000
    max-timer-jobs-per-acquisition: 10
    max-async-jobs-per-acquisition: 10
    reset-expired-jobs: true

server:
  port: 8080

logging:
  level:
    com.saga.orchestrator: DEBUG
    org.flowable: INFO
