plugins {
    id 'scala'
    id 'io.gatling.gradle' version '3.12.0.1'
}

group = 'com.saga.orchestrator'
version = '1.0.0'

repositories {
    mavenCentral()
}

// Required for Gatling plugin
ext {
    reportsDir = file("${buildDir}/reports/gatling")
}

dependencies {
    gatling 'io.gatling.highcharts:gatling-charts-highcharts:3.12.0'
    
    // Additional dependencies for JSON handling
    gatling 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    gatling 'com.fasterxml.jackson.module:jackson-module-scala_2.13:2.17.0'
}
