spring:
  application:
    name: payment-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

logging:
  level:
    com.saga.orchestrator.payment: DEBUG
